### ISSUE TITLE
Explanation for errors on validation step

### ISSUE THREAD

**Issue by neuropil** [soichih/sca-wf-conneval#4]
Further detials about the required file formats for the DWI, T1, bvec and bval files would be helpful. In addition, to clarify on the errors for why files fail to load. Also, individual validation checks for each file would help not have to load all 4 each time.

**Comment by soichih** [comment]
John,

Thank you for reporting this problem. The file upload feature seems to be broken. I will fix this ASAP.

**Comment by soichih** [comment]
John, I believe I've fixed this issue. Could you try submitting it again?

Also, may I ask how you found our application? Which workflow are you interested in running?

(update)

I forgot to mention. When you encounter validation error, you should be able to click the "Back" button and update only the file you'd like to re-upload by first clicking on the trash icon to remove it.

**Comment by neuropil** [comment]
Ok! I'll give it try! Thanks for your prompt assistance!

**Comment by neuropil** [comment]
Pre-processing worked!!
