### ISSUE TITLE
Transfer data between modules

### ISSUE THREAD

**Issue by neuropil** [soichih/sca-wf-conneval#6]
This processing portal is amazing!! Thank you so much for this effort. Is it possible to transfer processed data between modules. For example, if FREESURFER is run on a data set in the LIFE module, it would be helpful to be able to transfer those outputs to the connectome module. Rather than having to repeat the process for both.

**Comment by soichih** [comment]
Thanks! Sorry, you can't transfer derivatives between processes in our old UI. One of the main goal of our old app was to allow users to easily submit complex neuroscience workflows, so it has a very basic / limited workflow capability.

We are working on our new UI that allows data warehousing / custom workflow management. If you are interested, can you send me an email (hayashis@iu.edu) and I might be able to give you an early user access. :)

Thanks!
Soichi

**Comment by neuropil** [comment]
What you accomplished thus far is amazing!!!!! I've struggled to AFQ and LiFE up and running on Matlab for a while now. I would love to help out as a beta tester using early access. Let me know how I can help.

**Comment by francopestilli** [comment]
Dear @neuropil, Thank you very much!  We really would love to have you as beta-tester. Would you be kind to contact @soichih and me via email? 

We would like to help you make sure the apps are running properly for you and your data is normalized properly. This would, in turn, be very helpful for us and the project! 

franpest@indiana.edu and hayashis@iu.edu

Franco
